
import type { Metadata } from 'next'
import React from 'react'
import Register from './Register'


export const metadata: Metadata = {
    title: 'Register With Oslim-Event',
    description: 'Generated by create next app',
}

const page = () => {
    return (
        <div>
            <Register />
        </div>
    )
}

export default page